// @generated drizzle-zero signature:sha256:c21bb568782837ccb84cce74a4f014fae739aaf97be2ad6d66559a46ac51b6e7
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero"
import { createBuilder } from "@rocicorp/zero"
import type { ZeroCustomType } from "drizzle-zero"
import type { default as zeroSchema } from "../drizzle-zero.config"

const chatMessageTable = {
  name: "chatMessage",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    chatId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "chat_id",
    },
    authorId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "author_id",
    },
    body: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    editedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "edited_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
  },
  primaryKey: ["id"],
  serverName: "chat_message",
} as const
const chatParticipantTable = {
  name: "chatParticipant",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    chatId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "chat_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    joinedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "joined_at",
    },
  },
  primaryKey: ["id"],
  serverName: "chat_participant",
} as const
const chatReadStateTable = {
  name: "chatReadState",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    chatId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "chat_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    lastReadMessageId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "last_read_message_id",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "chat_read_state",
} as const
const projectTaskTable = {
  name: "projectTask",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "todo" | "in_progress" | "done",
    },
    position: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "project_task",
} as const
const resourceTable = {
  name: "resource",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "workspace_id",
    },
    parentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "parent_id",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "resource",
        "kind"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    icon: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdBy: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const
const resourceAgentTable = {
  name: "resourceAgent",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    model: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    persona: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    systemPrompt: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "system_prompt",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_agent",
} as const
const resourceAiChatTable = {
  name: "resourceAiChat",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    model: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    agentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "agent_id",
    },
    messages: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "resourceAiChat",
        "messages"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_ai_chat",
} as const
const resourceBookmarkTable = {
  name: "resourceBookmark",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    targetResourceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "target_resource_id",
    },
    externalUrl: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "external_url",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_bookmark",
} as const
const resourceChatTable = {
  name: "resourceChat",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as "dm" | "channel" | "thread",
    },
    targetResourceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "target_resource_id",
    },
    directKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "direct_key",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_chat",
} as const
const resourceFileTable = {
  name: "resourceFile",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    sizeBytes: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "size_bytes",
    },
    originalName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "original_name",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_file",
} as const
const resourceProjectTable = {
  name: "resourceProject",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "active" | "completed" | "archived",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_project",
} as const
const resourceWhiteboardTable = {
  name: "resourceWhiteboard",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    scene: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "resourceWhiteboard",
        "scene"
      >,
    },
    formatVersion: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "format_version",
    },
    revision: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_whiteboard",
} as const
const resourceWhiteboardAssetTable = {
  name: "resourceWhiteboardAsset",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    whiteboardId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "whiteboard_id",
    },
    mimeType: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    sizeBytes: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "size_bytes",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["whiteboardId", "id"],
  serverName: "resource_whiteboard_asset",
} as const
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const
const workspaceTable = {
  name: "workspace",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const
const workspaceMemberTable = {
  name: "workspaceMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "workspace_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as "owner" | "member",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "workspace_member",
} as const
const chatMessageRelationships = {
  chat: [
    {
      sourceField: ["chatId"],
      destField: ["id"],
      destSchema: "resourceChat",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const
const chatParticipantRelationships = {
  chat: [
    {
      sourceField: ["chatId"],
      destField: ["id"],
      destSchema: "resourceChat",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const
const chatReadStateRelationships = {
  chat: [
    {
      sourceField: ["chatId"],
      destField: ["id"],
      destSchema: "resourceChat",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  lastReadMessage: [
    {
      sourceField: ["lastReadMessageId"],
      destField: ["id"],
      destSchema: "chatMessage",
      cardinality: "one",
    },
  ],
} as const
const projectTaskRelationships = {
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "resourceProject",
      cardinality: "one",
    },
  ],
  creator: [
    {
      sourceField: ["createdBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const
const resourceAgentRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const
const resourceAiChatRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  agent: [
    {
      sourceField: ["agentId"],
      destField: ["id"],
      destSchema: "resourceAgent",
      cardinality: "one",
    },
  ],
} as const
const resourceBookmarkRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  target: [
    {
      sourceField: ["targetResourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const
const resourceChatRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  target: [
    {
      sourceField: ["targetResourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  participants: [
    {
      sourceField: ["id"],
      destField: ["chatId"],
      destSchema: "chatParticipant",
      cardinality: "many",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["chatId"],
      destSchema: "chatMessage",
      cardinality: "many",
    },
  ],
  readStates: [
    {
      sourceField: ["id"],
      destField: ["chatId"],
      destSchema: "chatReadState",
      cardinality: "many",
    },
  ],
} as const
const resourceFileRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const
const resourceProjectRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  tasks: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "projectTask",
      cardinality: "many",
    },
  ],
} as const
const resourceRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  creator: [
    {
      sourceField: ["createdBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  parent: [
    {
      sourceField: ["parentId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  children: [
    {
      sourceField: ["id"],
      destField: ["parentId"],
      destSchema: "resource",
      cardinality: "many",
    },
  ],
  chat: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resourceChat",
      cardinality: "one",
    },
  ],
  attachedThread: [
    {
      sourceField: ["id"],
      destField: ["targetResourceId"],
      destSchema: "resourceChat",
      cardinality: "one",
    },
  ],
} as const
const resourceWhiteboardAssetRelationships = {
  whiteboard: [
    {
      sourceField: ["whiteboardId"],
      destField: ["id"],
      destSchema: "resourceWhiteboard",
      cardinality: "one",
    },
  ],
} as const
const resourceWhiteboardRelationships = {
  resource: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  assets: [
    {
      sourceField: ["id"],
      destField: ["whiteboardId"],
      destSchema: "resourceWhiteboardAsset",
      cardinality: "many",
    },
  ],
} as const
const workspaceMemberRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const
const workspaceRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "workspaceMember",
      cardinality: "many",
    },
  ],
} as const
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    chatMessage: chatMessageTable,
    chatParticipant: chatParticipantTable,
    chatReadState: chatReadStateTable,
    projectTask: projectTaskTable,
    resource: resourceTable,
    resourceAgent: resourceAgentTable,
    resourceAiChat: resourceAiChatTable,
    resourceBookmark: resourceBookmarkTable,
    resourceChat: resourceChatTable,
    resourceFile: resourceFileTable,
    resourceProject: resourceProjectTable,
    resourceWhiteboard: resourceWhiteboardTable,
    resourceWhiteboardAsset: resourceWhiteboardAssetTable,
    user: userTable,
    workspace: workspaceTable,
    workspaceMember: workspaceMemberTable,
  },
  relationships: {
    chatMessage: chatMessageRelationships,
    chatParticipant: chatParticipantRelationships,
    chatReadState: chatReadStateRelationships,
    projectTask: projectTaskRelationships,
    resourceAgent: resourceAgentRelationships,
    resourceAiChat: resourceAiChatRelationships,
    resourceBookmark: resourceBookmarkRelationships,
    resourceChat: resourceChatRelationships,
    resourceFile: resourceFileRelationships,
    resourceProject: resourceProjectRelationships,
    resource: resourceRelationships,
    resourceWhiteboardAsset: resourceWhiteboardAssetRelationships,
    resourceWhiteboard: resourceWhiteboardRelationships,
    workspaceMember: workspaceMemberRelationships,
    workspace: workspaceRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "chatMessage" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChatMessage = Row<(typeof schema)["tables"]["chatMessage"]>
/**
 * Represents a row from the "chatParticipant" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChatParticipant = Row<(typeof schema)["tables"]["chatParticipant"]>
/**
 * Represents a row from the "chatReadState" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChatReadState = Row<(typeof schema)["tables"]["chatReadState"]>
/**
 * Represents a row from the "projectTask" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ProjectTask = Row<(typeof schema)["tables"]["projectTask"]>
/**
 * Represents a row from the "resource" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Resource = Row<(typeof schema)["tables"]["resource"]>
/**
 * Represents a row from the "resourceAgent" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceAgent = Row<(typeof schema)["tables"]["resourceAgent"]>
/**
 * Represents a row from the "resourceAiChat" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceAiChat = Row<(typeof schema)["tables"]["resourceAiChat"]>
/**
 * Represents a row from the "resourceBookmark" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceBookmark = Row<
  (typeof schema)["tables"]["resourceBookmark"]
>
/**
 * Represents a row from the "resourceChat" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceChat = Row<(typeof schema)["tables"]["resourceChat"]>
/**
 * Represents a row from the "resourceFile" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceFile = Row<(typeof schema)["tables"]["resourceFile"]>
/**
 * Represents a row from the "resourceProject" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceProject = Row<(typeof schema)["tables"]["resourceProject"]>
/**
 * Represents a row from the "resourceWhiteboard" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceWhiteboard = Row<
  (typeof schema)["tables"]["resourceWhiteboard"]
>
/**
 * Represents a row from the "resourceWhiteboardAsset" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceWhiteboardAsset = Row<
  (typeof schema)["tables"]["resourceWhiteboardAsset"]
>
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>
/**
 * Represents a row from the "workspace" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspace"]>
/**
 * Represents a row from the "workspaceMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkspaceMember = Row<(typeof schema)["tables"]["workspaceMember"]>

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema)
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema
  }
}
