import { drizzleZeroConfig } from "drizzle-zero"
import * as drizzleSchema from "../db/src/schema/index"

// Only browser-safe relational data belongs in Zero's client-visible schema.
// Auth credentials, sessions, invitation token hashes, and object storage keys
// intentionally remain API-only.
export default drizzleZeroConfig(drizzleSchema, {
  tables: {
    user: {
      id: true,
      name: true,
      email: true,
      image: true,
      createdAt: true,
      updatedAt: true,
    },
    workspace: {
      id: true,
      name: true,
      slug: true,
      createdAt: true,
      updatedAt: true,
    },
    workspaceMember: {
      id: true,
      workspaceId: true,
      userId: true,
      role: true,
      createdAt: true,
    },
    resource: {
      id: true,
      workspaceId: true,
      parentId: true,
      kind: true,
      name: true,
      description: true,
      icon: true,
      createdBy: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceFile: {
      id: true,
      mimeType: true,
      sizeBytes: true,
      originalName: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceProject: {
      id: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
    projectTask: {
      id: true,
      projectId: true,
      title: true,
      description: true,
      status: true,
      position: true,
      createdBy: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceBookmark: {
      id: true,
      targetResourceId: true,
      externalUrl: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceChat: {
      id: true,
      type: true,
      targetResourceId: true,
      directKey: true,
      createdAt: true,
      updatedAt: true,
    },
    chatParticipant: {
      id: true,
      chatId: true,
      userId: true,
      joinedAt: true,
    },
    chatMessage: {
      id: true,
      chatId: true,
      authorId: true,
      body: true,
      createdAt: true,
      editedAt: true,
      deletedAt: true,
    },
    chatReadState: {
      id: true,
      chatId: true,
      userId: true,
      lastReadMessageId: true,
      updatedAt: true,
    },
    resourceAgent: {
      id: true,
      model: true,
      persona: true,
      systemPrompt: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceAiChat: {
      id: true,
      model: true,
      agentId: true,
      messages: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceWhiteboard: {
      id: true,
      scene: true,
      formatVersion: true,
      revision: true,
      createdAt: true,
      updatedAt: true,
    },
    resourceWhiteboardAsset: {
      id: true,
      whiteboardId: true,
      mimeType: true,
      sizeBytes: true,
      createdAt: true,
    },
  },
})
