import {
  AiChat02Icon,
  AiUserIcon,
  Award01Icon,
  Book01Icon,
  Bookmark01Icon,
  Briefcase01Icon,
  Building01Icon,
  BulbIcon,
  Calendar03Icon,
  Camera01Icon,
  ChampionIcon,
  Chart01Icon,
  Chat01Icon,
  Clock01Icon,
  CloudIcon,
  CodeIcon,
  Database01Icon,
  File01Icon,
  Flag01Icon,
  Folder01Icon,
  GiftIcon,
  Globe02Icon,
  GraduationScrollIcon,
  HeartIcon,
  Home01Icon,
  Image01Icon,
  Key01Icon,
  Link01Icon,
  LockIcon,
  Mail01Icon,
  MapsLocation01Icon,
  MusicNote01Icon,
  Note01Icon,
  PieChartIcon,
  Pin02Icon,
  Rocket01Icon,
  Search01Icon,
  Settings01Icon,
  Shield01Icon,
  StarIcon,
  Table01Icon,
  Tag01Icon,
  Target01Icon,
  Task01Icon,
  UserGroupIcon,
  UserIcon,
  Video01Icon,
  WhiteboardIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons"
import type { IconSvgElement } from "@hugeicons/react"

export type ResourceIconOption = {
  name: string
  label: string
  icon: IconSvgElement
}

export const RESOURCE_ICON_OPTIONS: ResourceIconOption[] = [
  { name: "AiUserIcon", label: "AI agent", icon: AiUserIcon },
  { name: "AiChat02Icon", label: "AI chat", icon: AiChat02Icon },
  { name: "Home01Icon", label: "Home", icon: Home01Icon },
  { name: "Folder01Icon", label: "Folder", icon: Folder01Icon },
  { name: "File01Icon", label: "File", icon: File01Icon },
  { name: "Note01Icon", label: "Note", icon: Note01Icon },
  { name: "Table01Icon", label: "Table", icon: Table01Icon },
  { name: "Task01Icon", label: "Task", icon: Task01Icon },
  { name: "Bookmark01Icon", label: "Bookmark", icon: Bookmark01Icon },
  { name: "WhiteboardIcon", label: "Whiteboard", icon: WhiteboardIcon },
  { name: "StarIcon", label: "Star", icon: StarIcon },
  { name: "HeartIcon", label: "Heart", icon: HeartIcon },
  { name: "Rocket01Icon", label: "Rocket", icon: Rocket01Icon },
  { name: "BulbIcon", label: "Idea", icon: BulbIcon },
  { name: "Briefcase01Icon", label: "Briefcase", icon: Briefcase01Icon },
  { name: "Building01Icon", label: "Building", icon: Building01Icon },
  { name: "Calendar03Icon", label: "Calendar", icon: Calendar03Icon },
  { name: "Clock01Icon", label: "Clock", icon: Clock01Icon },
  { name: "UserIcon", label: "Person", icon: UserIcon },
  { name: "UserGroupIcon", label: "People", icon: UserGroupIcon },
  { name: "Globe02Icon", label: "Globe", icon: Globe02Icon },
  { name: "Link01Icon", label: "Link", icon: Link01Icon },
  { name: "CodeIcon", label: "Code", icon: CodeIcon },
  { name: "Database01Icon", label: "Database", icon: Database01Icon },
  { name: "Chart01Icon", label: "Chart", icon: Chart01Icon },
  { name: "PieChartIcon", label: "Pie chart", icon: PieChartIcon },
  { name: "Mail01Icon", label: "Mail", icon: Mail01Icon },
  { name: "Chat01Icon", label: "Chat", icon: Chat01Icon },
  { name: "Camera01Icon", label: "Camera", icon: Camera01Icon },
  { name: "Image01Icon", label: "Image", icon: Image01Icon },
  { name: "Video01Icon", label: "Video", icon: Video01Icon },
  { name: "MusicNote01Icon", label: "Music", icon: MusicNote01Icon },
  { name: "Book01Icon", label: "Book", icon: Book01Icon },
  {
    name: "GraduationScrollIcon",
    label: "Education",
    icon: GraduationScrollIcon,
  },
  { name: "Shield01Icon", label: "Shield", icon: Shield01Icon },
  { name: "LockIcon", label: "Lock", icon: LockIcon },
  { name: "Key01Icon", label: "Key", icon: Key01Icon },
  { name: "Settings01Icon", label: "Settings", icon: Settings01Icon },
  { name: "Search01Icon", label: "Search", icon: Search01Icon },
  { name: "Flag01Icon", label: "Flag", icon: Flag01Icon },
  { name: "Target01Icon", label: "Target", icon: Target01Icon },
  { name: "ChampionIcon", label: "Trophy", icon: ChampionIcon },
  { name: "Award01Icon", label: "Award", icon: Award01Icon },
  { name: "GiftIcon", label: "Gift", icon: GiftIcon },
  { name: "Tag01Icon", label: "Tag", icon: Tag01Icon },
  { name: "Pin02Icon", label: "Pin", icon: Pin02Icon },
  { name: "MapsLocation01Icon", label: "Location", icon: MapsLocation01Icon },
  { name: "CloudIcon", label: "Cloud", icon: CloudIcon },
  { name: "ZapIcon", label: "Energy", icon: ZapIcon },
]

const ICONS_BY_NAME = new Map(
  RESOURCE_ICON_OPTIONS.map((option) => [option.name, option])
)

export function getResourceIconOption(name?: string | null) {
  return name ? ICONS_BY_NAME.get(name) : undefined
}
